#!/usr/bin/env sh


DECLARATIONS=""
ARRAY="sqExport *pluginExports[] = {\n"

# read args one by one and place them into the corresponding array
for var in vm os $@
do
	DECLARATIONS="${DECLARATIONS}extern sqExport ${var}_exports[];\n"
    ARRAY="${ARRAY}\t ${var}_exports,\n"
done

ARRAY="${ARRAY}\t NULL\n};\n"
rm -f sqNamedPrims.h

echo "// this file has been autogenerated using gen_plugins_file.sh\n" >>sqNamedPrims.h
echo $DECLARATIONS >>sqNamedPrims.h
echo $ARRAY >>sqNamedPrims.h

