// this file has been autogenerated using gen_plugins_file.sh

extern sqExport vm_exports[];
extern sqExport os_exports[];
extern sqExport ADPCMCodecPlugin_exports[];
extern sqExport B2DPlugin_exports[];
extern sqExport BitBltPlugin_exports[];
extern sqExport DSAPrims_exports[];
extern sqExport ZipPlugin_exports[];
extern sqExport FFTPlugin_exports[];
extern sqExport FloatArrayPlugin_exports[];
extern sqExport LargeIntegers_exports[];
extern sqExport Matrix2x3Plugin_exports[];
extern sqExport X64SysVFFIPlugin_exports[];
extern sqExport SqueakNOSPlugin_exports[];
extern sqExport StarSqueakPlugin_exports[];

sqExport *pluginExports[] = {
	 vm_exports,
	 os_exports,
	 ADPCMCodecPlugin_exports,
	 B2DPlugin_exports,
	 BitBltPlugin_exports,
	 DSAPrims_exports,
	 ZipPlugin_exports,
	 FFTPlugin_exports,
	 FloatArrayPlugin_exports,
	 LargeIntegers_exports,
	 Matrix2x3Plugin_exports,
	 X64SysVFFIPlugin_exports,
	 SqueakNOSPlugin_exports,
	 StarSqueakPlugin_exports,
	 NULL
};

